#
# Module manifest for module 'FlameVault'
#
# Generated by: Strategickhaos DAO LLC
#
# Generated on: 12/15/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'FlameVault.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# ID used to uniquely identify this module
GUID = 'a7f8e3c2-1b4d-4e5f-9a7c-2d8e3f4a5b6c'

# Author of this module
Author = 'Strategickhaos DAO LLC'

# Company or vendor of this module
CompanyName = 'Strategickhaos DAO LLC'

# Copyright statement for this module
Copyright = '(c) 2025 Strategickhaos DAO LLC. All rights reserved.'

# Description of the functionality provided by this module
Description = 'FlameVault - Honeypot + Encrypted Secrets Engine. INV-080: Machine-bound encryption with honeypot trap for exposed credentials.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module
FunctionsToExport = @(
    'Initialize-FlameVault',
    'Set-FlameSecret',
    'Get-FlameSecret',
    'Set-FlameHoneypot',
    'Deploy-FlameTraps',
    'Get-FlameAlerts',
    'Export-FlameEnv'
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Security', 'Encryption', 'Honeypot', 'Secrets', 'Vault', 'DPAPI', 'StrategicKhaos')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/strategickhaos-dao-llc/skh-flamelang-StrategicKhaos-prefix-/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/strategickhaos-dao-llc/skh-flamelang-StrategicKhaos-prefix-'

        # ReleaseNotes of this module
        ReleaseNotes = 'Initial release: Machine-bound encryption with honeypot traps for credential protection'

    }

}

}
